# Generated by Django 5.2.8 on 2026-01-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id_alter_todolist_id_monthlyplan_and_more'),
        ('todo_lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='todo_list',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='todo_lists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo_lists.todolists'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='MonthlyPlan',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
        migrations.DeleteModel(
            name='WeeklyPlan',
        ),
    ]
